add_newline = true
right_format = "$username$hostname$time"

continuation_prompt = "â–¶â–¶ "

[line_break]
disabled = false

[character]
error_symbol = "[âŒ](bold red)"

[cmd_duration]
format = "took [$duration]($style) "

[time]
# time_format = "%T"
use_12hr = true
format = "ğŸ•™$time($style)"
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed red"
style_root = "bold dimmed cyan"
show_always = true
format = "[$user]($style) "

[hostname]
ssh_only = false
format = "[$hostname](bold 227) "
disabled = false

[directory]
format = "ïŠ [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ï„“ î‚  "
format = "[$symbol$branch]($style) "

[python]
format = "[${symbol}${pyenv_prefix}(${version})(($virtualenv))]($style) "

[conda]
ignore_base = false
format = '[$symbol$environment]($style) '
symbol = "ğŸ…’"