add_newline = true
right_format = "$username$hostname$time"

continuation_prompt = "â–¶â–¶ "

[line_break]
disabled = false

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "

[cmd_duration]
format = "took [$duration]($style) "

[time]
# time_format = "%T"
use_12hr = true 	
format = "ğŸ•™ $time($style)"
style = "bright-white"
disabled = false

[username]
style_user = "bold red"
style_root = "bold cyan"
show_always = true
format = "[$user]($style) "

[hostname]
ssh_only = false
format = "[$hostname](bold cyan) "
disabled = false

[directory]
format = " ïŠ [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ï„“ î‚  "
format = "[$symbol$branch]($style) "

[python]
format = "[${symbol}${pyenv_prefix}(${version})(($virtualenv))]($style) "

[conda]
ignore_base = false
format = '[$symbol$environment]($style) '
symbol = 'ğŸ…’" '
